local addonName, ns = ...

ns.AddonName = addonName
ns.MediaRoot = "Interface\\AddOns\\" .. addonName .. "\\Media\\"

ns.Mode = {
    TELEPORT = "teleport",
    PORTAL = "portal",
}

ns.Constants = {
    -- Saved-variable schema. 3 was the last TBC schema; 4 the first Forever
    -- one; 5 turned the cinematic camera on by default; 6 dropped the
    -- utility-mode and launcher-theme settings.
    VERSION = 6,
    CLASS_MAGE = "MAGE",
    FACTION_HORDE = "Horde",
    FACTION_ALLIANCE = "Alliance",
    ITEM_RUNE_TELEPORTATION = 17031,
    ITEM_RUNE_PORTALS = 17032,
    ITEM_HEARTHSTONE = 6948,
    ITEM_CRUMBLING_HEARTHSTONE = 282006,
    ITEM_ATIESH = 22589,
    SPELL_HEARTHSTONE = 8690,
    -- The "Reagent Economy" perk, one spell per class (docs/FOREVER-PROBE.md, run 2).
    REAGENT_ECONOMY_SPELLS = { 1225503, 1262636, 1262638, 1262643, 1262647, 1262650, 1262654, 1262662 },
    -- Hearth-type toys tried in order when owned (none measured yet on Forever).
    HEARTH_TOYS = {},
    DEFAULTS = {
        version = 6,
        showUnavailableKarazhan = true,
        cinematicCamera = true,
        hideGameUI = true,
        cameraOrbit = true,
        cameraCastAware = true,
        lockLauncher = false,
        launcherScale = 1.35,
        launcherGlow = "blue",
        actionBarPromptDismissed = false,
        showMinimapButton = true,
        showCompartment = true,
        soundsEnabled = true,
        hoverSoundsEnabled = true,
        animationsEnabled = true,
        idleAnimationsEnabled = true,
        hoverAnimationsEnabled = true,
        animationIntensity = 1.0,
        reagentDisplay = "auto",
        broadcastPortals = true,
        broadcastTeleports = false,
        broadcastOnStart = true,
        broadcastOnSuccess = false,
        confirmGroupedTeleport = true,
        debugFaction = "auto",
        debugTrace = false,
        soundChannel = "SFX",
        soundTheme = "addon",
        uiScale = 1.0,
        launcher = {
            point = "CENTER",
            x = -230,
            y = -20,
        },
        roulette = {
            point = "CENTER",
            x = 320,
            y = 60,
        },
        minimap = {
            minimapPos = 220,
            hide = false,
        },
        showcase = {},
    },
}

ns.Media = {
    REAGENT_ICON_TELEPORT = ns.MediaRoot .. "Icon_RuneTeleport_Custom_128.tga",
    REAGENT_ICON_PORTAL = ns.MediaRoot .. "Icon_RunePortal_Custom_128.tga",
    ICON_HEARTHSTONE_CUSTOM = ns.MediaRoot .. "Icon_Hearthstone_Custom_128.tga",
    -- The TBC hearth orb art (gold ring, blue stone), three states.
    HEARTH_ORB_NORMAL = ns.MediaRoot .. "HearthstoneOrb_Normal_1254x1254.tga",
    LAUNCHER_PORTAL = ns.MediaRoot .. "Launcher\\Portal_256.tga",
    LAUNCHER_POINTER = ns.MediaRoot .. "Launcher\\TipPointer_32x16.tga",
    CITY_ICON_ROOT = ns.MediaRoot .. "CityIcons\\",
    -- Generated by Tools/make_art.py (Media\Glass).
    RUNE_BAND = ns.MediaRoot .. "Glass\\RuneBand_512.tga",
    GLOW = ns.MediaRoot .. "Glass\\Glow_128.tga",
    MIST = ns.MediaRoot .. "Glass\\Mist_512.tga",
    DISC_RIM = ns.MediaRoot .. "Glass\\DiscRim_512.tga",
    DISC_RIM_DARK = ns.MediaRoot .. "Glass\\DiscRimDark_512.tga",
    WISPS_A = ns.MediaRoot .. "Glass\\WispsA_512.tga",
    WISPS_B = ns.MediaRoot .. "Glass\\WispsB_512.tga",
    NODE_RING = ns.MediaRoot .. "Glass\\NodeRing_128.tga",
    SPECULAR = ns.MediaRoot .. "Glass\\Specular_64.tga",
    TITLE_GLINT = ns.MediaRoot .. "Glass\\TitleGlint_64.tga",
    LINK_GLOW = ns.MediaRoot .. "Glass\\LinkGlow_256x32.tga",
    COMET = ns.MediaRoot .. "Glass\\Comet_64.tga",
    SHIMMER = ns.MediaRoot .. "Glass\\Shimmer_256.tga",
    ORBIT_DOTS = ns.MediaRoot .. "Glass\\OrbitDots_512.tga",
    -- Built-in circle mask, as FrameXML's CircleMask templates use.
    CIRCLE_MASK = "Interface\\CharacterFrame\\TempPortraitAlphaMask",
    WHITE = "Interface\\Buttons\\WHITE8X8",
    SOUND_OPEN = ns.MediaRoot .. "Sounds\\OGG\\PortalRoulette_Open.ogg",
    SOUND_CLOSE = ns.MediaRoot .. "Sounds\\OGG\\PortalRoulette_Close.ogg",
    SOUND_NODE_HOVER = ns.MediaRoot .. "Sounds\\OGG\\PortalRoulette_NodeHover.ogg",
    SOUND_NODE_CLICK = ns.MediaRoot .. "Sounds\\OGG\\PortalRoulette_NodeClick.ogg",
    SOUND_HEARTHSTONE_HOVER = ns.MediaRoot .. "Sounds\\OGG\\PortalRoulette_HearthstoneHover.ogg",
    SOUND_HEARTHSTONE_CLICK = ns.MediaRoot .. "Sounds\\OGG\\PortalRoulette_HearthstoneClick.ogg",
    SOUND_KARAZHAN_HOVER = ns.MediaRoot .. "Sounds\\OGG\\PortalRoulette_KarazhanHover.ogg",
    SOUND_ERROR = ns.MediaRoot .. "Sounds\\OGG\\PortalRoulette_Error.ogg",
}

-- Accent colours: teleport intent is arcane blue, portal intent violet.
ns.Colors = {
    TELEPORT = { 0.42, 0.58, 1.0 },
    PORTAL = { 0.66, 0.42, 1.0 },
    BONUS = { 0.66, 0.42, 1.0 },
    TEXT = { 1, 1, 1, 0.9 },
    MUTED = { 1, 1, 1, 0.6 },
    WARN = { 1, 0.32, 0.32 },
}
