-- ============================================================
-- Disc: the smoked-glass disc and the arcane light under it.
--
-- Visual target (the motion brief from the animated mockup):
--   * Energy wisps circulate slowly beneath the glass: two feathered,
--     broken-strand textures turning at different speeds, each with its own
--     slow opacity drift (never in sync), plus a few motes.
--   * Links are narrow streams of light (core, body, faint halo, faded
--     ends). A short comet travels outward along each, staggered, with a
--     quiet gap between passes. Hovering a node brightens its link, its
--     comet and its rim together; the others stay at idle.
--   * The glass, icons, labels and orb never move.
--
-- Driven by one per-frame updater (Disc.Update) while the wheel is open,
-- not by AnimationGroups: exact speeds, staggers and hover fades. The
-- updater frame is parented to WorldFrame so hiding the game UI does not
-- stop it (UIParent-parented tickers freeze when the UI is hidden).
-- All textures are generated by Tools/make_art.py.
-- ============================================================

local _, ns = ...

local Skin = ns.Skin
local Anim = ns.Anim
local Layout = ns.Layout
local M = ns.Media

local Disc = {}
ns.Disc = Disc

local TWO_PI = math.pi * 2

-- Wisp layers, as in the animated mockup: a slower one close to the
-- middle, and a faster one on top of it spanning the whole wheel.
-- texture key, size factor, seconds per turn, base alpha, drift period (s),
-- drift depth.
local LAYERS = {
    { "WISPS_B", 0.62, 40, 0.80, 9.1, 0.25 },
    { "WISPS_A", 1.00, 17, 0.60, 6.3, 0.30 },
    -- Small dots running around the outer ring: one full tour in 5 s.
    { "ORBIT_DOTS", 0.98, 5, 0.95, 3.7, 0.20 },
}

-- The diagonal light streak: every SHIMMER_EVERY seconds (plus a little
-- jitter) it crosses the disc from the top-left to the bottom-right.
local SHIMMER_EVERY, SHIMMER_TIME = 8, 1.6

-- Comets: travel time and the quiet gap between passes.
local TRAVEL = 1.0
local GAP_MIN, GAP_MAX = 1.6, 2.8

local function layerTexture(disc, file, size, sublevel)
    local tex = disc:CreateTexture(nil, "BORDER", nil, sublevel)
    tex:SetSize(size, size)
    tex:SetPoint("CENTER")
    tex:SetTexture(file)
    tex:SetBlendMode("ADD")
    if disc.glass.mask then
        tex:AddMaskTexture(disc.glass.mask)
    end
    return tex
end

function Disc.Create(root)
    local disc = CreateFrame("Frame", nil, root)
    disc:SetSize(Layout.DISC, Layout.DISC)
    disc:SetPoint("CENTER", root, "CENTER", 0, Layout.DISC_Y)
    disc:EnableMouse(false)
    disc.glass = Skin:Disc(disc, "disc")

    -- Faint blue illumination within the disc, strongest behind the orb.
    disc.inner = layerTexture(disc, M.GLOW, Layout.DISC * 0.8, 0)

    disc.layers = {}
    for i, spec in ipairs(LAYERS) do
        local tex = layerTexture(disc, M[spec[1]], Layout.DISC * spec[2], i)
        disc.layers[i] = { tex = tex, period = spec[3], base = spec[4], drift = spec[5], depth = spec[6],
                           phase = i * 1.7 }
    end

    -- Very faint etched markings, subordinate to the destinations.
    disc.runes = layerTexture(disc, M.RUNE_BAND, Layout.DISC * 0.98, 6)

    -- The occasional diagonal streak, clipped to the disc.
    disc.shimmer = layerTexture(disc, M.SHIMMER, Layout.DISC * 1.2, 7)
    disc.shimmer:Hide()
    disc.shimmerWait, disc.shimmerT = 1.0, -1

    disc.links = {}
    disc.time = 0
    Disc.SetIntent(disc, ns.Mode.TELEPORT)
    return disc
end

------------------------------------------------------------
-- Links
------------------------------------------------------------

local function newLink(disc, key)
    local parent = disc.glass.top or disc
    local line = parent:CreateLine(nil, "ARTWORK", nil, 2)
    line:SetTexture(M.LINK_GLOW)
    line:SetThickness(14)
    line:SetBlendMode("ADD")
    local comet = parent:CreateTexture(nil, "ARTWORK", nil, 4)
    comet:SetSize(46, 46)
    comet:SetTexture(M.COMET)
    comet:SetBlendMode("ADD")
    comet:Hide()
    local link = {
        disc = disc, line = line, comet = comet, glow = 0, target = 0,
        -- Staggered first pass so the spokes never flash together.
        wait = (key * 0.71) % 1 * GAP_MAX, progress = -1, seed = (key * 0.37) % 1,
    }
    disc.links[key] = link
    return link
end

-- Place link `key` from the centre outward to a node at (x, y), stopping
-- at the node's rim. `inner` is where it starts (orb rim, or disc rim for
-- a satellite). `level` is how alive the link is: 1 full, between 0 and 1
-- a dimmer flow (not learned yet), 0 dim and without comets (unavailable).
function Disc.Link(disc, key, x, y, inner, nodeSize, color, level)
    local link = disc.links[key] or newLink(disc, key)
    local len = math.sqrt(x * x + y * y)
    local ux, uy = x / len, y / len
    local stop = (nodeSize or Layout.NODE) / 2 + 2
    link.sx, link.sy = ux * inner, uy * inner
    link.ex, link.ey = x - ux * stop, y - uy * stop
    link.line:SetStartPoint("CENTER", disc, link.sx, link.sy)
    link.line:SetEndPoint("CENTER", disc, link.ex, link.ey)
    link.comet:SetRotation(math.atan2(uy, ux))
    link.color = color or ns.Colors.TELEPORT
    if level == nil or level == true then
        level = 1
    elseif level == false then
        level = 0
    end
    link.level = level
    link.active = level > 0
    link.line:Show()
    Disc.PaintLink(link)
end

function Disc.HideLink(disc, key)
    local link = disc.links[key]
    if link then
        link.line:Hide()
        link.comet:Hide()
    end
end

-- Hover emphasis for one link (smoothed in Update).
function Disc.SetLinkLit(disc, key, lit)
    local link = disc.links[key]
    if link then
        link.target = lit and 1 or 0
    end
end

function Disc.PaintLink(link)
    local c = link.color
    local idle = link.active and (0.16 + 0.22 * link.level) or 0.16
    local a = idle + (0.95 - idle) * link.glow
    link.line:SetVertexColor(c[1], c[2], c[3], a)
end

------------------------------------------------------------
-- Intent tint (teleport blue / portal violet)
------------------------------------------------------------

function Disc.SetIntent(disc, mode)
    local c = mode == ns.Mode.PORTAL and ns.Colors.PORTAL or ns.Colors.TELEPORT
    disc.inner:SetVertexColor(c[1], c[2], c[3], 0.22)
    disc.runes:SetVertexColor(c[1] + 0.2, c[2] + 0.2, 1, 0.16)
    for i, layer in ipairs(disc.layers) do
        -- The slower layer leans violet, the faster one follows the intent:
        -- depth from two hues.
        local mix = i == 1 and ns.Colors.PORTAL or c
        layer.r, layer.g, layer.b = mix[1], mix[2], mix[3]
        layer.tex:SetVertexColor(mix[1], mix[2], mix[3], layer.base)
    end
end

------------------------------------------------------------
-- The per-frame update (only while the wheel is open)
------------------------------------------------------------

-- Move `value` toward `target`, taking inTime to rise fully and outTime
-- to fall fully.
function Disc.Approach(value, target, elapsed, inTime, outTime)
    if target > value then
        return math.min(target, value + elapsed / inTime)
    end
    return math.max(target, value - elapsed / outTime)
end

function Disc.Update(disc, elapsed)
    local idle = Anim.Enabled("idle")
    local t = disc.time + elapsed
    disc.time = t

    for _, layer in ipairs(disc.layers) do
        if idle then
            layer.tex:SetRotation(-TWO_PI * t / layer.period)
        end
        local drift = idle and math.sin(TWO_PI * t / layer.drift + layer.phase) or 0
        local a = layer.base * (1 - layer.depth * 0.5 + layer.depth * 0.5 * drift)
        layer.tex:SetVertexColor(layer.r, layer.g, layer.b, a)
    end
    if idle then
        disc.runes:SetRotation(TWO_PI * t / 160)
    end
    Disc.UpdateShimmer(disc, elapsed, idle)

    for _, link in pairs(disc.links) do
        if link.line:IsShown() then
            local before = link.glow
            link.glow = Disc.Approach(link.glow, link.target, elapsed, 0.18, 0.28)
            if link.glow ~= before then
                Disc.PaintLink(link)
            end
            Disc.UpdateComet(link, elapsed, idle)
        end
    end
end

function Disc.UpdateShimmer(disc, elapsed, idle)
    local tex = disc.shimmer
    if not idle then
        tex:Hide()
        return
    end
    if disc.shimmerT < 0 then
        disc.shimmerWait = disc.shimmerWait - elapsed
        if disc.shimmerWait > 0 then
            return
        end
        disc.shimmerT = 0
    end
    disc.shimmerT = disc.shimmerT + elapsed / SHIMMER_TIME
    local p = disc.shimmerT
    if p >= 1 then
        disc.shimmerT = -1
        disc.shimmerWait = SHIMMER_EVERY + (disc.time % 3)
        tex:Hide()
        return
    end
    -- From beyond the top-left to beyond the bottom-right of the disc.
    local travel = Layout.DISC * 0.95
    local off = (p * 2 - 1) * travel
    tex:ClearAllPoints()
    tex:SetPoint("CENTER", disc, "CENTER", off * 0.7071, -off * 0.7071)
    local fade = math.sin(p * math.pi)
    tex:SetVertexColor(0.85, 0.9, 1, 0.22 * fade)
    tex:Show()
end

function Disc.UpdateComet(link, elapsed, idle)
    local comet = link.comet
    if not idle or not link.active then
        comet:Hide()
        return
    end
    if link.progress < 0 then
        link.wait = link.wait - elapsed
        if link.wait > 0 then
            comet:Hide()
            return
        end
        link.progress = 0
    end
    -- A hovered link runs a little faster, brighter and more often.
    link.progress = link.progress + elapsed * (1 + link.glow * 0.5) / TRAVEL
    local p = link.progress
    if p >= 1 then
        link.progress = -1
        link.seed = (link.seed * 7.31 + 0.37) % 1
        link.wait = (GAP_MIN + (GAP_MAX - GAP_MIN) * link.seed) * (1 - link.glow * 0.6)
        comet:Hide()
        return
    end
    local eased = p * p * (3 - 2 * p)
    comet:ClearAllPoints()
    comet:SetPoint("CENTER", link.disc, "CENTER",
        link.sx + (link.ex - link.sx) * eased, link.sy + (link.ey - link.sy) * eased)
    -- Fade in out of the orb, fade out before the destination rim.
    local fade = math.min(1, p / 0.15) * math.min(1, (1 - p) / 0.3)
    local c = link.color
    local strength = link.level + (1 - link.level) * link.glow -- hover lifts a dim flow too
    comet:SetVertexColor(c[1] * 0.6 + 0.4, c[2] * 0.6 + 0.4, 1, fade * (0.65 + 0.35 * link.glow) * strength)
    comet:Show()
end

------------------------------------------------------------
-- Start / stop
------------------------------------------------------------

local ticker
function Disc.Start(disc)
    if not ticker then
        ticker = CreateFrame("Frame", nil, WorldFrame)
    end
    ticker:SetScript("OnUpdate", function(_, elapsed)
        Disc.Update(disc, elapsed)
        if ns.Roulette and ns.Roulette.UpdateNodes then
            ns.Roulette:UpdateNodes(elapsed)
        end
    end)
    ticker:Show()
    Disc.ticker = ticker
end

function Disc.Stop(disc)
    if ticker then
        ticker:SetScript("OnUpdate", nil)
    end
    for _, link in pairs(disc.links) do
        link.comet:Hide()
        link.glow, link.target, link.progress = 0, 0, -1
        Disc.PaintLink(link)
    end
end
