-- ============================================================
-- Disc: the smoked-glass disc and the arcane light under it.
--
-- Visual target (the motion brief from the animated mockup):
--   * Mist, broken curls and fine filaments circulate beneath stationary
--     glass, with independent slow rotation, breathing and opacity drift.
--   * Links are narrow streams of light (core, body, faint halo, faded
--     ends). A short comet travels outward along each, staggered, with a
--     quiet gap between passes. Hovering a node brightens its link, its
--     comet and its rim together; the others stay at idle.
--   * The glass, icons, labels and orb never move.
--
-- Driven by one per-frame updater (Disc.Update) while the wheel is open,
-- not by AnimationGroups: exact speeds, staggers and hover fades. The
-- updater frame is parented to WorldFrame so hiding the game UI does not
-- stop it (UIParent-parented tickers freeze when the UI is hidden).
-- All textures are generated by Tools/make_art.py.
-- ============================================================

local _, ns = ...

local Skin = ns.Skin
local Anim = ns.Anim
local Layout = ns.Layout
local M = ns.Media

local Disc = {}
ns.Disc = Disc

local TWO_PI = math.pi * 2
-- Rune etching sways four degrees out and back over four seconds; the
-- glass rim itself stays fixed. Two seconds per leg, easing at both ends.
local RUNE_SWAY, RUNE_PERIOD = math.rad(2), 4

-- texture key, size factor, seconds per turn, base alpha, drift period (s),
-- drift depth, initial angle (radians), size breathing fraction.
local LAYERS = {
    { "MIST",       1.02,  53, 0.34, 11.3, 0.24, 0.7, 0.018 },
    { "WISPS_A",    0.98,  31, 0.52,  8.7, 0.24, 2.1, 0.012 },
    { "WISPS_B",    0.92, -47, 0.38,  7.1, 0.20, 4.3, 0.008 },
    { "ORBIT_DOTS", 0.98,  16, 0.52,  5.9, 0.16, 1.4, 0 },
}

-- The diagonal light streak: every SHIMMER_EVERY seconds (plus a little
-- jitter) it crosses the disc from the top-left to the bottom-right.
local SHIMMER_EVERY, SHIMMER_TIME = 8, 1.6

-- Comets: travel time and the quiet gap between passes.
local TRAVEL = 1.0
local GAP_MIN, GAP_MAX = 1.6, 2.8

local function layerTexture(disc, file, size, sublevel)
    local tex = disc:CreateTexture(nil, "BORDER", nil, sublevel)
    tex:SetSize(size, size)
    tex:SetPoint("CENTER")
    tex:SetTexture(file)
    tex:SetBlendMode("ADD")
    if disc.glass.mask then
        tex:AddMaskTexture(disc.glass.mask)
    end
    return tex
end

function Disc.Create(root)
    local disc = CreateFrame("Frame", nil, root)
    disc:SetSize(Layout.DISC, Layout.DISC)
    disc:SetPoint("CENTER", root, "CENTER", 0, Layout.DISC_Y)
    disc:EnableMouse(false)
    disc.glass = Skin:Disc(disc, "disc")

    -- Faint blue illumination within the disc, strongest behind the orb.
    disc.inner = layerTexture(disc, M.GLOW, Layout.DISC * 0.8, 0)

    disc.layers = {}
    for i, spec in ipairs(LAYERS) do
        local tex = layerTexture(disc, M[spec[1]], Layout.DISC * spec[2], i)
        disc.layers[i] = { tex = tex, period = spec[3], base = spec[4], drift = spec[5], depth = spec[6],
                           phase = i * 1.7, angle = spec[7], size = Layout.DISC * spec[2],
                           breath = spec[8] }
        tex:SetRotation(spec[7])
    end

    -- Very faint etched markings, subordinate to the destinations.
    disc.runes = layerTexture(disc, M.RUNE_BAND, Layout.DISC * 0.98, 6)

    -- The occasional diagonal streak, clipped to the disc.
    disc.shimmer = layerTexture(disc, M.SHIMMER, Layout.DISC * 1.2, 7)
    disc.shimmer:Hide()
    disc.shimmerWait, disc.shimmerT = 1.0, -1

    disc.links = {}
    disc.time = 0
    Disc.SetIntent(disc, ns.Mode.TELEPORT)
    return disc
end

------------------------------------------------------------
-- Links
------------------------------------------------------------

local function newLink(disc, key)
    local parent = disc.glass.top or disc
    local line = parent:CreateLine(nil, "ARTWORK", nil, 2)
    line:SetTexture(M.LINK_GLOW)
    line:SetThickness(14)
    line:SetBlendMode("ADD")
    local comet = parent:CreateTexture(nil, "ARTWORK", nil, 4)
    comet:SetTexture(M.COMET)
    comet:SetBlendMode("ADD")
    comet:Hide()
    local link = {
        disc = disc, line = line, comet = comet, glow = 0, target = 0,
        -- Staggered first pass so the spokes never flash together.
        wait = (key * 0.71) % 1 * GAP_MAX, progress = -1, seed = (key * 0.37) % 1,
        initialWait = (key * 0.71) % 1 * GAP_MAX,
    }
    disc.links[key] = link
    return link
end

-- Place link `key` from the centre outward to a node at (x, y), stopping
-- at the node's rim. `inner` is where it starts (orb rim, or disc rim for
-- a satellite). `level` is how alive the link is: 1 full, between 0 and 1
-- a dimmer flow (not learned yet), 0 dim and without comets (unavailable).
function Disc.Link(disc, key, x, y, inner, nodeSize, color, level)
    local link = disc.links[key] or newLink(disc, key)
    local len = math.sqrt(x * x + y * y)
    local ux, uy = x / len, y / len
    local stop = (nodeSize or Layout.NODE) / 2 + 2
    link.sx, link.sy = ux * inner, uy * inner
    link.ex, link.ey = x - ux * stop, y - uy * stop
    link.length = math.max(0, len - inner - stop)
    link.pulseSize = math.min(40, link.length * 0.45)
    link.comet:SetSize(link.pulseSize, link.pulseSize)
    link.line:SetStartPoint("CENTER", disc, link.sx, link.sy)
    link.line:SetEndPoint("CENTER", disc, link.ex, link.ey)
    link.comet:SetRotation(math.atan2(uy, ux))
    link.color = color or ns.Colors.TELEPORT
    if level == nil or level == true then
        level = 1
    elseif level == false then
        level = 0
    end
    link.level = level
    link.active = level > 0 and link.length > 0
    link.line:Show()
    Disc.PaintLink(link)
end

function Disc.HideLink(disc, key)
    local link = disc.links[key]
    if link then
        link.line:Hide()
        link.comet:Hide()
        link.glow, link.target, link.progress = 0, 0, -1
        link.wait = link.initialWait
    end
end

-- Hover emphasis for one link (smoothed in Update).
function Disc.SetLinkLit(disc, key, lit)
    local link = disc.links[key]
    if link then
        local entered = lit and link.target == 0
        link.target = lit and 1 or 0
        if entered and link.active and link.progress < 0 and Anim.Enabled("hover")
            and Anim.Intensity() > 0 then
            link.wait = math.min(link.wait, 0.08)
        end
        link.glow = Anim.ApproachHover(link.glow, link.target, 0)
        Disc.PaintLink(link)
    end
end

function Disc.PaintLink(link)
    local c = link.color
    local idle = link.active and (0.16 + 0.22 * link.level) or 0.16
    local a = idle + (0.95 - idle) * link.glow * Anim.HoverStrength()
    link.line:SetVertexColor(c[1], c[2], c[3], a)
end

------------------------------------------------------------
-- Intent tint (teleport blue / portal violet)
------------------------------------------------------------

function Disc.SetIntent(disc, mode)
    local c = mode == ns.Mode.PORTAL and ns.Colors.PORTAL or ns.Colors.TELEPORT
    disc.inner:SetVertexColor(c[1], c[2], c[3], 0.22)
    disc.runes:SetVertexColor(c[1] + 0.2, c[2] + 0.2, 1, 0.16)
    for i, layer in ipairs(disc.layers) do
        -- Just the sparse filaments lean violet; smoke follows intent.
        local mix = i == 3 and ns.Colors.PORTAL or c
        layer.r, layer.g, layer.b = mix[1], mix[2], mix[3]
        layer.tex:SetVertexColor(mix[1], mix[2], mix[3], layer.base * (0.55 + 0.45 * Anim.Intensity()))
    end
end

------------------------------------------------------------
-- The per-frame update (only while the wheel is open)
------------------------------------------------------------

function Disc.Update(disc, elapsed)
    local intensity = Anim.Intensity()
    local idle = Anim.Enabled("idle") and intensity > 0
    -- Pausing idle motion freezes its phase; re-enabling does not jump ahead.
    if idle then disc.time = disc.time + elapsed end
    local t = disc.time

    for _, layer in ipairs(disc.layers) do
        if idle then
            layer.tex:SetRotation(layer.angle - TWO_PI * t / layer.period)
            if layer.breath ~= 0 then
                local size = layer.size * (1 + layer.breath * intensity * math.sin(TWO_PI * t / (layer.drift * 1.7) + layer.phase))
                layer.tex:SetSize(size, size)
            end
        end
        local drift = idle and math.sin(TWO_PI * t / layer.drift + layer.phase) or 0
        local a = layer.base * (0.55 + 0.45 * intensity)
            * (1 - layer.depth * 0.5 + layer.depth * 0.5 * drift * intensity)
        layer.tex:SetVertexColor(layer.r, layer.g, layer.b, a)
    end
    if idle then
        disc.runes:SetRotation(RUNE_SWAY * intensity * (1 - math.cos(TWO_PI * t / RUNE_PERIOD)))
    end
    Disc.UpdateShimmer(disc, elapsed, idle)

    for _, link in pairs(disc.links) do
        if link.line:IsShown() then
            local before = link.glow
            link.glow = Anim.ApproachHover(link.glow, link.target, elapsed)
            if link.glow ~= before or link.paintedIntensity ~= intensity then
                link.paintedIntensity = intensity
                Disc.PaintLink(link)
            end
            Disc.UpdateComet(link, elapsed, idle)
        end
    end
end

function Disc.UpdateShimmer(disc, elapsed, idle)
    local tex = disc.shimmer
    if not idle then
        tex:Hide()
        return
    end
    if disc.shimmerT < 0 then
        disc.shimmerWait = disc.shimmerWait - elapsed
        if disc.shimmerWait > 0 then
            return
        end
        disc.shimmerT = 0
    end
    disc.shimmerT = disc.shimmerT + elapsed / SHIMMER_TIME
    local p = disc.shimmerT
    if p >= 1 then
        disc.shimmerT = -1
        disc.shimmerWait = SHIMMER_EVERY + (disc.time % 3)
        tex:Hide()
        return
    end
    -- From beyond the top-left to beyond the bottom-right of the disc.
    local travel = Layout.DISC * 0.95
    local off = (p * 2 - 1) * travel
    tex:ClearAllPoints()
    tex:SetPoint("CENTER", disc, "CENTER", off * 0.7071, -off * 0.7071)
    local fade = math.sin(p * math.pi)
    tex:SetVertexColor(0.85, 0.9, 1, 0.12 * fade * Anim.Intensity())
    tex:Show()
end

function Disc.UpdateComet(link, elapsed, idle)
    local comet = link.comet
    if not idle or not link.active then
        comet:Hide()
        link.progress = -1
        return
    end
    if link.progress < 0 then
        link.wait = link.wait - elapsed
        if link.wait > 0 then
            comet:Hide()
            return
        end
        link.progress = 0
    end
    local hover = Anim.Enabled("hover") and link.glow * Anim.Intensity() or 0
    -- Constant speed, including when hover changes during a visible pass.
    link.progress = link.progress + elapsed / TRAVEL
    local p = link.progress
    if p >= 1 then
        link.progress = -1
        link.seed = (link.seed * 7.31 + 0.37) % 1
        link.wait = (GAP_MIN + (GAP_MAX - GAP_MIN) * link.seed) * (1 - hover * 0.6)
        comet:Hide()
        return
    end
    -- Keep the entire longitudinal texture footprint between the rims.
    -- The head is at u=.82, hence +.32*size ahead of the anchor; its tail
    -- starts at u=.25. A <=45%-of-spoke quad leaves >=55% for travel.
    local along = link.pulseSize * 0.5 + (link.length - link.pulseSize) * p
    local fraction = along / link.length
    comet:ClearAllPoints()
    comet:SetPoint("CENTER", link.disc, "CENTER",
        link.sx + (link.ex - link.sx) * fraction, link.sy + (link.ey - link.sy) * fraction)
    -- Fade in out of the orb, fade out before the destination rim.
    local fade = math.min(1, p / 0.15) * math.min(1, (1 - p) / 0.3)
    local c = link.color
    local strength = link.level + (1 - link.level) * hover
    comet:SetVertexColor(c[1] * 0.6 + 0.4, c[2] * 0.6 + 0.4, 1,
        fade * (0.65 + 0.35 * hover) * strength * Anim.Intensity())
    comet:Show()
end

------------------------------------------------------------
-- Start / stop
------------------------------------------------------------

local ticker
function Disc.Start(disc)
    if not ticker then
        ticker = CreateFrame("Frame", nil, WorldFrame)
    end
    ticker:SetScript("OnUpdate", function(_, elapsed)
        Disc.Update(disc, elapsed)
        if ns.Roulette and ns.Roulette.UpdateNodes then
            ns.Roulette:UpdateNodes(elapsed)
        end
    end)
    ticker:Show()
    Disc.ticker = ticker
end

function Disc.Stop(disc)
    if ticker then
        ticker:SetScript("OnUpdate", nil)
    end
    disc.shimmer:Hide()
    disc.shimmerT, disc.shimmerWait = -1, 1
    for _, link in pairs(disc.links) do
        link.comet:Hide()
        link.glow, link.target, link.progress = 0, 0, -1
        link.wait = link.initialWait
        Disc.PaintLink(link)
    end
end
